name = "SPCUtil"
uuid = "4bfda58d-8e2d-4d3c-8407-d9fbf285e053"
authors = ["Sean P. Cornelius <spcornelius@gmail.com>"]
version = "0.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
SlurmClusterManager = "c82cd089-7bf7-41d7-976b-6b5d413cbe0a"
